/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    Composer: typeof import('./src/components/Composer.vue')['default']
    ConversationPanel: typeof import('./src/components/ConversationPanel.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExecutionTimeline: typeof import('./src/components/ExecutionTimeline.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HitCard: typeof import('./src/components/HitCard.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    PhaseStream: typeof import('./src/components/PhaseStream.vue')['default']
    QueryBox: typeof import('./src/components/QueryBox.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusDot: typeof import('./src/components/StatusDot.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TimelineItem: typeof import('./src/components/TimelineItem.vue')['default']
  }
}
