/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    Composer: typeof import('./src/components/Composer.vue')['default']
    ConversationPanel: typeof import('./src/components/ConversationPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExecutionTimeline: typeof import('./src/components/ExecutionTimeline.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HitCard: typeof import('./src/components/HitCard.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    PhaseStream: typeof import('./src/components/PhaseStream.vue')['default']
    QueryBox: typeof import('./src/components/QueryBox.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusDot: typeof import('./src/components/StatusDot.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TimelineItem: typeof import('./src/components/TimelineItem.vue')['default']
  }
}
